//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_05.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day_05.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seeds: 3136945476 509728956 1904897211 495273540 1186343315 66026055 1381149926 11379441 4060485949 190301545 444541979 351779229 1076140984 104902451 264807001 60556152 3676523418 44140882 3895155702 111080695
        ///
        ///seed-to-soil map:
        ///2122609492 2788703865 117293332
        ///751770532 1940296486 410787026
        ///2652142963 2905997197 464992562
        ///3442443139 3721315963 573651333
        ///3117135525 2356966701 133002244
        ///742051533 3370989759 9718999
        ///2239902824 720032349 393589935
        ///1162557558 58715335 661317014
        ///1823874572 2489968945  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RealInput {
            get {
                return ResourceManager.GetString("RealInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seeds: 79 14 55 13
        ///
        ///seed-to-soil map:
        ///50 98 2
        ///52 50 48
        ///
        ///soil-to-fertilizer map:
        ///0 15 37
        ///37 52 2
        ///39 0 15
        ///
        ///fertilizer-to-water map:
        ///49 53 8
        ///0 11 42
        ///42 0 7
        ///57 7 4
        ///
        ///water-to-light map:
        ///88 18 7
        ///18 25 70
        ///
        ///light-to-temperature map:
        ///45 77 23
        ///81 45 19
        ///68 64 13
        ///
        ///temperature-to-humidity map:
        ///0 69 1
        ///1 0 69
        ///
        ///humidity-to-location map:
        ///60 56 37
        ///56 93 4.
        /// </summary>
        internal static string TestInput {
            get {
                return ResourceManager.GetString("TestInput", resourceCulture);
            }
        }
    }
}
