//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day_01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9cbncbxclbvkmfzdnldc
        ///jjn1drdffhs
        ///3six7
        ///38rgtnqqxtc
        ///rxszdkkv3j8kjhbm
        ///54nzzddht8ninelrkkseightseven6
        ///6fourmnvkgnthjtnjqkr
        ///nineninezsstmkone4sjnlbldcrj4eight
        ///3rdnfkvrx4twoqgeightqkgmn
        ///6mlhponeglrzrvbsseven
        ///five8spgxz8
        ///3three2dfourfour58
        ///9q
        ///two45
        ///five8mpkpdfiveeightfourseven
        ///93threefive3three92
        ///6jdzeightnineone1sclhzrnrjxfive
        ///6nseven16lbztpbbzthree8five
        ///eight6mntljvbfrmftsffchsix4
        ///4twosixvnhjl
        ///8d
        ///eightsevenvqvzlqxkbm6rqhsgqpnine7twonex
        ///seven96
        ///ck8tv6
        ///2mcddqpnbxssmrc6
        ///zsfbkrjjqpbbone6six [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RealInput {
            get {
                return ResourceManager.GetString("RealInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1abc2
        ///pqr3stu8vwx
        ///a1b2c3d4e5f
        ///treb7uchet.
        /// </summary>
        internal static string TestInput {
            get {
                return ResourceManager.GetString("TestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two1nine
        ///eightwothree
        ///abcone2threexyz
        ///xtwone3four
        ///4nineeightseven2
        ///zoneight234
        ///7pqrstsixteen.
        /// </summary>
        internal static string TestInput2 {
            get {
                return ResourceManager.GetString("TestInput2", resourceCulture);
            }
        }
    }
}
